import type { Metadata } from "next";
import { Inter, Roboto, Poppins, Baloo_Bhai_2 } from "next/font/google";
import Navbar from "./(components)/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });
const poppins = Poppins({ subsets: ["latin"], weight: "400"});
const baloobhai = Baloo_Bhai_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} ${roboto.className} ${baloobhai.className}`}>
        
      <Navbar />

      {children}
      </body>
    </html>
  );
}
